### ISSUE TITLE
"Killed - processing time exceeded" error when using Boost.PO

### ISSUE THREAD

**Issue by k15tfu** [mattgodbolt/compiler-explorer#933] opened 2018-05-21 10:01 UTC
https://godbolt.org/g/SQTnRP

**Comment by mattgodbolt** [comment] 2018-05-21 15:30
Compiling with some boost libraries takes a while on the compilation nodes:

```
ubuntu@ip-172-30-2-147:/tmp$ time /opt/compiler-explorer/clang-trunk/bin/clang++ -std=c++17 -fno-rtti -isystem /opt/compiler-explorer/libs/boost_1_67_0  -S -o test.S test.cc
real	0m8.298s
user	0m2.444s
sys	0m0.228s
```

I don't have a good solution for this: understandably I need to have some kind of limit on the compilation time.

That said, most of the issue is the fact that the compilers and libraries are stored on a network drive, which isn't very fast to access. If I copy the boost headers to a local disk and try again:

```
ubuntu@ip-172-30-2-147:/tmp$ time /opt/compiler-explorer/clang-trunk/bin/clang++ -std=c++17 -fno-rtti -isystem /tmp/foo/  -S -o test.S test.cc

real	0m3.324s
user	0m2.340s
sys	0m0.328s
```

The situation is much better. We have an open bug for this: #730 - some kind of caching might help, or a complete rethink about how we ship compilers and libraries.

I'm closing this bug in favour of #730 - feel free to comment further there.

**Closed by mattgodbolt** 2018-05-21 15:30 UTC
Labels: enhancement
