### ISSUE TITLE
Linux pasting does not work

### ISSUE THREAD

**Issue by sesse** [mattgodbolt/compiler-explorer#1040] opened 2018-08-09 17:24 UTC
Hi,

For whatever reason, pasting does not work. I'm using Linux, where middle-mouse button is used to paste, and it simply does nothing in the compiler explorer. There's no reaction whatsoever.

FWIW, Ctrl-V does work, but it is from a different clipboard, which rarely contains the wanted text. The only workaround I know of is to middle-paste the code in some other window, copy it with Ctrl-C and then Ctrl-V it into the compiler explorer.

**Comment by RabsRincon** [comment] 2018-08-11 08:15
Hi @sesse thanks for the report and for taking so long to get an answer back!

This is a known problem (At least since [March 2017](https://github.com/mattgodbolt/compiler-explorer/issues/359#issuecomment-290341904)), but it still puzzles me as to why it's happening. We tell Monaco editor to enable said clipboard (On by default), and I doubt it's a bug on their side, as it would have been reported elsewhere.

So we must be the ones to blame here. So far I have not been able to pinpoint the exact reason why this happens, so it seems the problem is here to stay for a while, until someone more knowledgeable than me is able to find the cause/solution.

So there is no happy ending for this yet, sorry! I'll leave this open so we don't forget about it :)

**Comment by sesse** [comment] 2018-08-11 09:37
I tried looking into the code, but it was a bewildering jungle of 820 modules in various JavaScript dialects and build systems, and I could never really get to the Monaco source so I could insert console.log() in it :-)

But comparing the page that I linked to with how a local copy of the compiler explorer works (by setting event listener breakpoints in Chrome), it seems that mouseDown, paste and beforePaste are somehow never triggered for middle-button click in the compiler explorer—but it is in the Microsoft page.

It's possible that upgrading Monaco would help. I don't know.

**Comment by RabsRincon** [comment] 2019-07-22 13:30
Hi! Sorry for all the time it took for this to get fixed. We were stuck on an old Monaco Editor version for a while. It does now seem to be fixed, so I'll (finally!) close this issue.

Thanks again for taking the time to report it and  for being so patient! :)

**Closed by RabsRincon** 2019-07-22 13:30 UTC
Labels: bug, help wanted, ui
