### ISSUE TITLE
Infinite loop/hang in LRU cache under some circumstances

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#568] opened 2017-10-09 18:53 UTC
Can get browser to hang with stack:

```
trim [Line: 306, Col: 1], lru-cache.js
LRUCache.prototype.set [Line: 214, Col: 1], lru-cache.js
Anonymous function [Line: 76, Col: 1], compiler-service.js
fire [Line: 3317, Col: 1], jquery.js
self.fireWith [Line: 3447, Col: 1], jquery.js
done [Line: 9272, Col: 1], jquery.js
Anonymous function [Line: 9514, Col: 1], jquery.js
wrapped [Line: 474, Col: 1], raven.js
[Worker#1 workerMain.js#editorWorkerService ()]
```

By playing around with errors etc, something like:

1. go to https://godbolt.org/g/YL9ES9
2. change it to return std::move(s + "rawr;" (with the error) and wait for the result
3. fix the syntax error and it freezes

(though hard to repro)

**Comment by mknejp** [comment] 2017-10-09 19:52
Can only reproduce with this specific link https://godbolt.org/g/MrukAn

**Comment by mattgodbolt** [comment] 2017-10-10 12:48
We've hit anothe rissue in updating this: the library we use is no longer compatible with our archaic build process. We're looking to fix that too. Thanks for your patience

**Comment by RabsRincon** [comment] 2018-01-13 23:47
This is dependant on [mattgodbolt/jw/webpack](https://github.com/mattgodbolt/compiler-explorer/tree/jw/webpack) branch. Moving to enchancement to be done after @jaredwy merges (Good luck with that!)

**Comment by jaredwy** [comment] 2018-02-08 21:59
@RabsRincon I have tried to get this to hang. It looks like it is now fixed. Any objections to closing this one out?

**Comment by RabsRincon** [comment] 2018-02-08 23:30
None at all :)

**Closed by RabsRincon** 2018-02-08 23:30 UTC
Labels: enhancement, tracking
