### ISSUE TITLE
[BUG] Errors in the output window in dark theme are not readable

### ISSUE THREAD

**Issue by mpusz** [mattgodbolt/compiler-explorer#1584] opened 2019-09-14 16:19 UTC
**Describe the bug**
When there is a compilation error in the output window it is nearly not visible in the dark theme. Please make it more visible (i.e. make it a lighter red color).

**Link**
https://godbolt.org/z/qNWF94

**Screenshots**
![image](https://user-images.githubusercontent.com/506260/64910947-2d440780-d71c-11e9-836c-9d34910ecd86.png)

**Comment by RabsRincon** [comment] 2019-09-14 16:45
Hi! Thanks for reporting it. @mattgodbolt submitted an issue right before you did, so I'll mark this as a duplicate of #1583 and track the issue there :)

**Closed by RabsRincon** 2019-09-14 16:45 UTC
Labels: bug, duplicate, ui
