### ISSUE TITLE
Cortex M Support missing from gcc ????

### ISSUE THREAD

**Issue by fordp2002** [mattgodbolt/compiler-explorer#247] opened 2017-01-26 10:09 UTC
I try compiling with -mcpu=cortex-m0 -mthumb on the gcc versions and it throws errors. A great use for compiler explorer is checking the efficiency for code and comparing the code generated for different ARM cores.

Maybe consider a drop down for selecting ARM targets ?

**Comment by haneefmubarak** [comment] 2017-01-26 10:20
Could you give us an example link where compiler-explorer throws such errors? It seems to be working just fine [here](https://godbolt.org/g/rLzbZv).

**Comment by fordp2002** [comment] 2017-01-26 14:27
It was the link on this [page](http://stackoverflow.com/questions/35133829/does-arm-gcc-have-a-builtin-function-for-the-assembly-rev-instruction) that did not work,

**Comment by mattgodbolt** [comment] 2017-01-26 14:51
Using that link and adding the flags: https://godbolt.org/g/4wl7Wd

```<source>: In function 'unsigned int foo(unsigned int)':
<source>:1:32: sorry, unimplemented: Thumb-1 hard-float VFP ABI
unsigned int foo(unsigned int a)
^
Compiler exited with result code 1```

It's not clear to me why this fails, whereas the gcc 5.4.1 succeeds (as per @haneefmubarak 's link). Maybe it was fixed in 5.4.1?

The 5.4.1 compiler is `gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-g++` from the embedded toolkit. 5.4 is `/usr/bin/aarch64-linux-gnu-g++` from an Ubuntu `apt get install` of the compiler.

**Comment by fordp2002** [comment] 2017-01-26 16:16
Looks like the compiler is defaulting to Hard Float which never exists on Cortex M0 - Cortex M3.
Maybe adding the soft-float flags will fix it?

**Comment by haneefmubarak** [comment] 2017-01-26 19:32
Testing through all the 32-bit ARM GCC versions on the page appears to show a regression in 5.4 that was resolved in 5.4.1. For 5.4, forcing the soft float flag (either `-mfloat-abi=soft` or `-mfloat-abi=softfp`) seems to make it work.

My guess here would be that in 5.4, something happened to make GCC assume hardware floating point support and make it the default, but since GCC knows the Cortex-M0 has no FP support, it fails to compile. While it may look weird that a function with no floating-point functionality depends on FP support, the ARM ABI (calling conventions, how the stack is utilized, etc.) varies depending on whether FP is implemented in hardware or emulated.

Unless we want to patch around GCC's options by version, I think it would be best to leave it as is.

**Comment by fordp2002** [comment] 2017-01-26 22:14
No need to change GCC, maybe my idea of a drop down for ARM targets would solve both issues as well as making the site easier to use!

Thanks for getting to the bottom of my issue.

**Comment by mattgodbolt** [comment] 2019-10-26 17:06
We have a number of ARM compilers and hacks now: gonna close this one for the sake of not having so many open issues that _seem_ addressed. Please let me know if this isn't the case!

**Closed by mattgodbolt** 2019-10-26 17:06 UTC
Labels: compiler-issue, lang-c++

**Comment by dkm** [comment] 2024-02-14 08:34
Do you know what would be missing in our configuration of gcc? I can add this to my todo list of things to look at, but that may take some time. Any hint welcome :)

IIUC, M0 doesn't have hardfloat, only an optional extension can be used. Do you mean that by default, gcc should use soft float, and only use hardware if asked?

**Comment by CookiePLMonster** [comment] 2024-02-14 09:47
> Do you know what would be missing in our configuration of gcc? I can add this to my todo list of things to look at, but that may take some time. Any hint welcome :)
> 
> IIUC, M0 doesn't have hardfloat, only an optional extension can be used. Do you mean that by default, gcc should use soft float, and only use hardware if asked? Or maybe the error is incorrect and gcc should emit valid insn whatever the option?

To be fair, I'm not sure. It is weird however that I need to set this option in order to get software **integer** division generated. Is this really related to the FPU ABI? Considering it's integer math, it feels like this option should not be relevant in this context.

**Comment by dkm** [comment] 2024-02-14 10:35
Integer division is still something that is usually done by the hardware or by some soft emulation (e.g. libgcc). I can have a look and see how that works on cortex-m0, will be good for my general culture

**Comment by CookiePLMonster** [comment] 2024-02-14 11:00
> I can have a look and see how that works on cortex-m0, will be good for my general culture

Looking at how Raspberry Pi Pico SDK does it, they seem to only set `-mcpu=cortex-m0plus -mthumb"` for GCC:
https://github.com/raspberrypi/pico-sdk/blob/master/cmake/preload/toolchains/pico_arm_gcc.cmake

They don't set it for Clang either:
https://github.com/raspberrypi/pico-sdk/blob/master/cmake/preload/toolchains/pico_arm_clang_arm.cmake

**Comment by dkm** [comment] 2024-02-14 15:57
Sure, but they probably rely on a specific toolchain that may have different default.

See from the doc https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf they install the debian package... So I did that, and the result for your code is:
```
divideme:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, lr}
	bl	__aeabi_uidiv
	@ sp needed
	pop	{r4, pc}
	.size	divideme, .-divideme
	.ident	"GCC: (15:13.2.rel1-1) 13.2.1 20231009"
```
And the actual call by the driver is:
```
COLLECT_GCC_OPTIONS='-Os' '-mcpu=cortex-m0plus' '-S' '-o' '-' '-v' '-mfloat-abi=soft' '-mthumb' '-mlibarch=armv6s-m' '-march=armv6s-m'
 /usr/lib/gcc/arm-none-eabi/13.2.1/cc1 -quiet -v -imultilib thumb/v6-m/nofp -D__USES_INITFINI__ bob.c -quiet -dumpbase bob.c -dumpbase-ext .c -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb -mlibarch=armv6s-m -march=armv6s-m -Os -version -o -
```
So the driver is using `-mfloat-abi=soft` by default... So the issue is "why" this different default, and is there a "best" default? We can change this kind of things for the following release if really needed...

**Comment by CookiePLMonster** [comment] 2024-02-14 15:58
> So the issue is "why" this different default, and is there a "best" default? We can change this kind of things for the following release if really needed...

Considering that M0/M0+ has no hardfp, defaulting to `soft` is probably reasonable I'd say.

**Comment by dkm** [comment] 2024-02-14 17:46
True. I wonder why this is not the case for our config. I'll keep this open and have a look. If there's an easy fix, I'll see to change this for the next build.

**Comment by TamarChristinaArm** [comment] 2024-02-14 18:16
> I see that ct-ng has a setting for softfp: "auto, soft, hard". But that's not bound to any particular `mcpu`. So that will probably change the default for all target? Maybe @TamarChristinaArm (who introduced the arm-trunk config here) has some insight? :).

I did so because armhf (`arm-unknown-linux-gnueabihf`) is the Tier-1 target for GCC development, no embedded target is Tier-1 so for daily checks it's the most useful. Though the `--with-fpu=neon` should be `--with-fpu=auto` these days.

> I can change the default, but I fear that we'll get a "why do I need to enable FPU? My `mcpu` should be enough".

The issue with changing it is that it then forces everyone to specify what they want through either adding an architecture or cpu. My understanding (and from looking at https://godbolt.org/) is that a distinction is already being made between linux hf targets and embedded targets (those are the `(none)` in the list).

So it sounds to me more like that you want an additional soft target (or auto) trunk build. and it's probably a good idea to split the Armhf compilers from the `(none)` compilers in that list.

**Comment by dkm** [comment] 2024-02-15 21:15
Thanks @TamarChristinaArm , we'll probably split the ARM some more then.
