### ISSUE TITLE
[BUG] libstdc++ glibc version mismatch when executing clang-built code

### ISSUE THREAD

**Issue by tronthomas** [mattgodbolt/compiler-explorer#1740] opened 2019-12-18 23:32 UTC
**Describe the bug**

> ./output.s: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./output.s)

 results when trying to use std::stringstream with clang compiler

**To Reproduce**
Attempt to compile and link the code below using the x86-64 clang 9.0.0 compiler with the following compiler flags: 

> -std=c++17

```
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <sstream>

using std::string;

namespace {
    auto textToInt(const string& input) {
        auto result = 0;

        auto sign = 1;

        auto start = input.begin();
        if (*start == '-') {
            sign = -1;
            ++start;
        }

        using std::domain_error;
        try {
            std::for_each(start, input.end(), [&result, &input](auto letter){
                if (std::isdigit(letter) == false) {
                    std::stringstream stream;
                    stream << "'" << input << "' is not a valid integer";
                    throw domain_error(stream.str().c_str());
                }
                int digit = letter - '0';
                result *= 10;
                result += digit;
            });
        }
        catch (domain_error&) {
            return 0;
        }

        return result * sign;
    }
}

int main() {
    string input {"abc"};

    std::cout << ::textToInt(input) << '\n';

    return 0;
}
```
**Expected behavior**
The code should compile and link successfully

**Link**
If applicable, please provide a link to Compiler Explorer to help explain your problem.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Safari
 - Version  13.0.4 (14608.4.9.1.4)

**Additional context**
If the use of std::stringstream is removed, the program will compile and link successfully

**Comment by mattgodbolt** [comment] 2019-12-19 15:02
Hi: did you have the "Execute" button ticked? It's really helpful if you link the Compiler Explorer link as this has all the information we need to diagnose the issue.

**Comment by tronthomas** [comment] 2019-12-19 16:19
I do not see any “Execute” button, where is it supposed to be?
How does someone provide the Compiler Explorer link?
The link the web browser is just https://godbolt.org <https://godbolt.org/> which doesn’t seem like that would be very useful.

**Comment by mattgodbolt** [comment] 2019-12-19 16:53
Hi! Sorry, the execute button is the `./a.out` button.

To share a link, go to the top right and click "Share". That will generate a unique short link of the form `godbolt.org/z/123123` which captures all the settings and code you have in your browser. You can share that to allow another person to open up the website exactly as you saw it.

**Comment by tronthomas** [comment] 2019-12-19 17:02
Yes, I do have the ./a.out button ticked.

Here is the share link:
https://godbolt.org/z/MzPhdX

**Comment by mattgodbolt** [comment] 2019-12-19 18:35
Thanks! If you untick that, the example works: I was pretty sure this was a problem with executing the program and not with compiling or linking it, and your link let me confirm that. Thanks!

**Comment by apmorton** [comment] 2020-03-07 08:47
closing as a duplicate of #1780

**Closed by apmorton** 2020-03-07 08:47 UTC
Labels: bug, duplicate
