### ISSUE TITLE
Some ASM words are lowercase in one window and uppercase in another which makes it visually different

### ISSUE THREAD

**Issue by sirinath** [mattgodbolt/compiler-explorer#308] opened 2017-03-04 05:37 UTC
![image](https://cloud.githubusercontent.com/assets/637415/23576421/aec12afc-00ca-11e7-9066-ef89db3239b6.png)

**Comment by sirinath** [comment] 2017-03-04 05:37
Also the grey highlighter is missing in one window.

**Comment by haneefmubarak** [comment] 2017-03-04 22:34
Those are specific to various compilers and the stylistic choices of their authors, which were often made with specific intents in mind as to code comprehension during error checking, etc. As for the purplish-grey highlight, that's caused by different compilers' consideration of which pieces of input code correspond to which pieces of output assembly. In this picture, GCC seems to consider the end of the function to correspond to the epilogue (which is reasonable, since the _epilogue_ goes at the _end_), whereas Clang appears to consider the return statement to correspond to the epilogue (also reasonable, seeing as a `return` statement marks the _end_ of execution.

Overall, I'd be against taking any action against this issue, but if this was to be resolved in code, I'd hope that it was done client-side as a switchable setting, not as something altered server-side.

**Comment by mattgodbolt** [comment] 2017-03-05 17:15
Thanks both. I'm afraid I agree with Haneef here. CE shows what the compiler generates, warts and all.

In the beta UI I have a separate issue open for making the diff UI case and whitespace insensitive, which might involve some kind of (optional) filtering of the output. Tgat could try to mitigate the differences. However the line attribution is completely out of scope for CE.

**Comment by mattgodbolt** [comment] 2017-03-05 17:16
Will leave this open to remind me to consider some kind of filter to make whitespace and case insensitive

**Comment by mattgodbolt** [comment] 2019-10-29 02:56
Returning to take a look, and I don't think I can fix this in any reasonable way. Thanks for raising the issue, but I'm going to close as wont-fix, sorry.

**Closed by mattgodbolt** 2019-10-29 02:56 UTC
Labels: enhancement, question, ui, wont-fix
