### ISSUE TITLE
rust nightly is broken

### ISSUE THREAD

**Issue by Rijenkii** [mattgodbolt/compiler-explorer#1197] opened 2018-11-29 12:03 UTC
Compiler output:
```
error: couldn't load codegen backend "/opt/compiler-explorer/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so": "librustc_codegen_ssa-e1d3d19c5f25a20e.so: cannot open shared object file: No such file or directory"

Compiler returned: 1
```

**Comment by RabsRincon** [comment] 2018-12-08 20:45
Thanks for the heads up, we have been looking into what's causing it for a bit now (Sorry we did not say a word!) Marking this as duplicate of #1165 :)

**Closed by RabsRincon** 2018-12-08 20:45 UTC
Labels: bug, compiler-issue, lang-rust
