### ISSUE TITLE
problem running CE locally

### ISSUE THREAD

**Issue by cppchedy** [mattgodbolt/compiler-explorer#294] opened 2017-02-21 16:27 UTC
I have a problem with CE when used locally.
it keep printing this message without stopping:

`/home/vagrant/Documents/compiler-explorer/app.js:68
var gitReleaseName = child_process.execSync('git rev-parse HEAD').toString().t
                                   ^
TypeError: Object #<Object> has no method 'execSync'
    at Object.<anonymous> (/home/vagrant/Documents/compiler-explorer/app.js:68:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
Program /usr/bin/nodejs ./app.js --language C++ exited with code 8
`

**Comment by mattgodbolt** [comment] 2017-02-21 16:33
Thanks for the report! Sorry this is an issue...

Duplicate of #188

**Closed by mattgodbolt** 2017-02-21 16:33 UTC
