### ISSUE TITLE
Show GCC tree/RTL dump not working

### ISSUE THREAD

**Issue by pree-jackie** [mattgodbolt/compiler-explorer#642] opened 2017-11-24 10:17 UTC
The drop-down list in Show GCC tree/RTL dump feature is not working ( Pass dump to display  drop-down list not appearing when clicked). I don't know whether it is drop-down list but it's icon seems like a drop-down list. If I'm wrong please tell me how to use that feature. 
System details:
ubuntu 16.04 xenial and mozilla firefox browser 
Thanks

**Comment by RabsRincon** [comment] 2017-11-24 12:09
Hello, sorry to hear you're having problems!
Could you please post an image of what you're describing so we can get a clearer picture of your issue? Thanks :)

cc @dkm who implemented it in first place

**Comment by pree-jackie** [comment] 2017-11-24 12:14
![k](https://user-images.githubusercontent.com/18092207/33210152-0a4247f4-d13f-11e7-939d-d51a6f3e9472.png)

**Comment by pree-jackie** [comment] 2017-11-24 12:15
see the  right most tab, It's a drop down list.

**Comment by dkm** [comment] 2017-11-24 13:01
Won't work with clang, only GCC. Sorry, I've already opened a ticket for this : #638 
The UI should be explicit about that.

**Comment by dkm** [comment] 2017-12-08 13:28
@RabsRincon this is a duplicate of now-closed #638. Maybe you could merge them ?

**Comment by RabsRincon** [comment] 2017-12-08 13:44
You're right. Good catch!

**Closed by RabsRincon** 2017-12-08 13:44 UTC
Labels: bug, ui
