### ISSUE TITLE
[BUG] MSVC 64-bit compilers are under x86 (rather than x86-64) heading

### ISSUE THREAD

**Issue by rconde01** [mattgodbolt/compiler-explorer#1688] opened 2019-11-19 14:23 UTC
**Describe the bug**
The 64-bit msvc compilers should be under a x86-64 heading, but they're under a x86 heading

**To Reproduce**
- Open CE.
- Open the compile dropdown
- See the incorrect header

**Expected behavior**
Should show the x86-64 header

**Screenshots**
![image](https://user-images.githubusercontent.com/354158/69154509-2041ec80-0aae-11ea-8124-b9541d22b049.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by mattgodbolt** [comment] 2019-11-19 14:27
Thanks: this is a duplicate of #1593 and we're stuck on Microsoft fixing it :(

**Closed by mattgodbolt** 2019-11-19 14:27 UTC
Labels: bug
