### ISSUE TITLE
allow demangling to be disabled

### ISSUE THREAD

**Issue by zygoloid** [mattgodbolt/compiler-explorer#532] opened 2017-09-21 20:21 UTC
I use compiler explorer to investigate how a range of compilers handle certain code patterns, and one of the things I care about is how they mangle names. Applying a demangler to the assembly output therefore makes the stock Compiler Explorer installation useless to me for this purpose (especially because demangling is lossy).

**Comment by mattgodbolt** [comment] 2017-09-21 21:33
Thanks! This is a duplicate of #285 but definitely underlines how important this should be. We'll prioritise accordingly.

**Closed** 2017-09-21 21:33 UTC

**Comment by mattgodbolt** [comment] 2017-09-22 15:34
In case you missed it; we fixed #285 and the update's been pushed to the live site. Thanks again for reporting it!
