### ISSUE TITLE
Fortran no longer working

### ISSUE THREAD

**Issue by LadaF** [mattgodbolt/compiler-explorer#234] opened 2017-01-12 09:23 UTC
This

http://gcc.godbolt.org/#%7B%22version%22%3A3%2C%22filterAsm%22%3A%7B%22labels%22%3Atrue%2C%22directives%22%3Atrue%2C%22commentOnly%22%3Atrue%2C%22intel%22%3Atrue%7D%2C%22compilers%22%3A%5B%7B%22sourcez%22%3A%22ATBOFMEMBNgKgDTAEoHUBQI3ALwnwJxEB0AHACwBMArAecANTABsxA7AQMwHWUCiAWkpwAKsAHACxAAw9KBaYM6i4cSkwCMM6Rualqg8iridxwLRsrTppToObH6TVtU7NOnfgILHqmYAAOoACWAHYALvBIaP7godBAA%3D%22%2C%22compiler%22%3A%22%2Fopt%2Fgcc-4.9.0%2Fbin%2Fg%2B%2B%22%2C%22options%22%3A%22-x%20f95%20-O3%20-march%3Dnative%22%7D%5D%7D

used to correctly compile Fortran code. Why is none of the GCC compiled with Fortran support now? It should be extremely easy to compile it as well.

**Comment by mattgodbolt** [comment] 2017-01-12 14:16
Thanks: I had honestly never known fortran would "just work" - I certainly never intended for it to do so!

All the GCCs are built with a script that only enables C and C++.  I can rebuild all the GCCs (at some expense of time), with fortran enabled. I guess a separate "fortran.godbolt.org" could be made too, which then uses the flags to build fortran, limits the compilers to those supporting it, and also then uses Fortran syntax highlighting.

Thanks for reporting!

**Comment by rcoacci** [comment] 2017-01-18 15:31
It would awesome to have fortran.godbolt.org and use it to compare assembly from Fortran with the assembly from C/C++. Would help to dispell (or confirm!) lots of myths.

**Comment by dev-zero** [comment] 2017-10-13 07:33
Well, this seems to work again. The rest of this issue seems like a duplicate of #549

**Comment by partouf** [comment] 2018-10-19 21:18
Hi, Fortran is now added as a separate language thanks to @dbroemmel 's efforts! let us know if you have any trouble with it

**Closed by partouf** 2018-10-19 21:18 UTC
Labels: compiler-issue, new-compilers
