### ISSUE TITLE
Strange constexpr-related issue with Clang

### ISSUE THREAD

**Issue by dodomorandi** [mattgodbolt/compiler-explorer#904] opened 2018-04-18 10:30 UTC
I fall into a strange issue, related to constexpr-ness of the `std::next` function when compiling with Clang **without `-stdlib=libc++`**. I discussed the issue [on stackoverflow](https://stackoverflow.com/questions/49895627/clang-stdnext-libstdc-and-constexpr-ness), and it looks like there is some sort of strange issue with Clang and the libstdc++ headers.

Please give a brief look to the discussion just to have an idea of what is happening. We think that the problem is related to clang, but it is not reproducible in every system. If you could perform some tests, it would be easier to find the cause of the issue -- maybe it is a matter of versions. Thanks!

**Comment by RabsRincon** [comment] 2018-04-18 10:52
Hi @dodomorandi! Thanks for the heads up, we really appreciate it. #903 is a direct duplicate of this issue (@eyalroz was faster than you reporting the problem), so I'll close this one in favour of that one. Feel free to keep an eye on it :)

We will be sure to check it out as soon as possible and report back what we find/how we can fix it.

:)

**Closed by RabsRincon** 2018-04-18 10:52 UTC
