### ISSUE TITLE
Incorrect line wrapping for compiler error

### ISSUE THREAD

**Issue by ilAYAli** [mattgodbolt/compiler-explorer#401] opened 2017-04-24 07:49 UTC
Safari: Version 10.1.1 (12603.2.3)

Example of wrapped message in error box:

    x86-64-clang 4.0.0: error expected ';' after return state
    ement

Screenshot:
http://imgur.com/a/e1YkK

**Comment by RabsRincon** [comment] 2017-05-08 16:15
After a bit of "Let's try to fix this", I'll mark this as a Monaco limitation. There is very litle we can do. 
Anyway I'll leave this one open as a reminder in case Monaco implements something for this.
 But I have -1 faith on that so...

**Comment by badeip** [comment] 2017-05-08 18:02
I found a workaround.
Install e.g  [_Stylish_](https://safari-extensions.apple.com/details/?id=com.sobolev.stylish-5555L95H45) or similar.

Associate the following with godbolt.org

    * {
        font-family: inherit !important;
    }

    html {
        font-family: 'Helvetica Monospaced' !important;
        font-size: 16px;
    }

**Comment by RabsRincon** [comment] 2017-09-27 21:57
Sorry for taking this long to get an answer. (I'm currently looking thru the backlog of issues and just rediscovered this, oops)

So I think your solution is even worse than the probelm, as the error tooltip would look like this with that css
![image](https://user-images.githubusercontent.com/5364255/30939940-8a91c19c-a3df-11e7-82f8-184c71f7d148.png)

Note that it seems like `word-warp: break-word` won't work either, probably because something Monaco does with its text. Will keep investigating

**Comment by mattgodbolt** [comment] 2018-10-23 02:20
_Might_ be fixed. The original image has retired, so I had to infer what it looks like. The newline happens at a word boundary:

![image](https://user-images.githubusercontent.com/633973/47331047-1b5b0100-d640-11e8-9231-67b814bb1771.png)

https://godbolt.org/z/fODKpi is how I was reproducing this.

Was the original issue broken wrapping, or the fact it wrapped at all, do either of you remember?

**Comment by RabsRincon** [comment] 2018-10-23 06:10
Broken wrapping was in fact the issue. Closing as solved :)

**Closed by RabsRincon** 2018-10-23 06:10 UTC
Labels: bug, help wanted, tracking, ui
