### ISSUE TITLE
Error while setting up own compiler

### ISSUE THREAD

**Issue by Vm900** [mattgodbolt/compiler-explorer#468] opened 2017-06-21 18:32 UTC
Hi
How do i get it to use my own compiler:
![compiler-explorer](https://user-images.githubusercontent.com/9399631/27400569-61976ac2-56b8-11e7-8043-9751ad6913c7.PNG)

Thanks

**Comment by mattgodbolt** [comment] 2017-06-21 23:55
Hi,

I really need to write this up somewhere!

Compilers are loaded from the properties files in `etc/config/*.properties`. This is a terrible system, I'm sorry. Usually the best way is to create a `etc/config/c++.local.properties` file -- any property listed here will override any same-named property elsewhere. It also is marked to not be checked into `git`, which is handy.

The property you need to set is `compilers` - which is a colon-separated list of compiler names, for example `compilers=gcc:clang`. Then, for each compiler you need to define at least two properties: `compiler.NAME.exe` and `compiler.NAME.name`. The `exe` should list the path. So, for example:

```
compilers=gcc:clang
compiler.gcc.exe=/usr/bin/g++
compiler.gcc.name=G++
compiler.clang.exe=/usr/bin/clang++
compiler.clang.name=Clang
```

Hopefully that will get you going. If you have troubles you can run `make` with `EXTRA_ARGS` including `--debug`, for example:

```
$ make EXTRA_ARGS="--debug"
```

**Comment by mattgodbolt** [comment] 2017-06-22 13:09
@Vm900 did this answer your question?

**Comment by Vm900** [comment] 2017-06-22 15:43
@mattgodbolt Sorry for the late reply.
Apparently it hasn't worked Matt.The same error message keeps
popping up

**Comment by mattgodbolt** [comment] 2017-06-22 16:55
Do you have a compiler at /usr/bin/clang++ ?

**Comment by Vm900** [comment] 2017-06-22 17:03
@mattgodbolt Yes i do 

clang: /usr/bin/clang /usr/lib/clang /usr/include/clang /usr/share/clang

**Comment by mattgodbolt** [comment] 2017-06-22 19:14
When CE is trying to execute `/usr/bin/clang++` it is getting `ENOENT` which means it isn't finding it.

What happens if you type:

```/usr/bin/clang++```

on the command-line?  I see this:

```
$ /usr/bin/clang++
clang: error: no input files
```

**Comment by mattgodbolt** [comment] 2017-06-22 19:16
If that works...can you check you don't have any spaces around the exe line in the properties file? e.g. no spaces between `clang.exe` and the equals and the path. The output above appears to show there's no spaces but I thought I'd check...

**Comment by Vm900** [comment] 2017-06-22 20:37
@mattgodbolt Hi,
I snuck this to the top of your app.js
--------------------------------------------------------------------------------
(function() {
    var childProcess = require("child_process");
    var oldSpawn = childProcess.spawn;
    function mySpawn() {
        console.log('spawn called');
        console.log(arguments);
        var result = oldSpawn.apply(this, arguments);
        return result;
    }
    childProcess.spawn = mySpawn;
})();

------------------------------------------------------------------------------------
And here is what i got.
![compiler-explorer](https://user-images.githubusercontent.com/9399631/27454768-fd31423e-5792-11e7-9330-c0eecc31c8d6.PNG)

**Comment by mattgodbolt** [comment] 2017-06-22 21:23
What is this `/mnt/c/tmp` ?  Are you running on Windows Subsystem for Linux?

**Comment by mattgodbolt** [comment] 2017-06-22 21:25
assuming you are there is a WSL bug that prevents node from spawning. I believe it's on the path to being fixed. @AndrewPardoe has a branch with some fixes in https://github.com/AndrewPardoe/compiler-explorer -- I hope to merge his fixes upon my return from vacation (~a week or so!)

**Comment by AndrewPardoe** [comment] 2017-06-22 21:36
Running under Ubuntu on Windows should work fine if you're using a Linux node.js and just the Linux compilers. My changes are to help in getting MSVC to run properly. And the Windows bug Matt mentions has to do with spawning Windows processes from bash, not bash processes. 

@Vm900 you should be able to get the stock version of CE running under Ubuntu on Windows without any changes. Which also means that there shouldn't be /mnt/c/tmp anywhere in your logs. It should just be using bash paths.

**Comment by mattgodbolt** [comment] 2017-06-22 21:38
Maybe I'm confused about what @vm900 is doing. I don't have the information
needed to debug their issue as I'm waiting to hear back about whether
`/usr/bin/clang++` can be run from a normal shell.

**Comment by admo** [comment] 2017-10-31 19:16
Hi,
I've found that problem is caused by cwd property of the spawned process. In lib/exec.js line 47 there is:
`cwd: process.env.tmpDir`
However, on WSL (Ubuntu 16.04) process.env.tmpDir is /mnt/c/tmp, which does not exists on my setup. 
This field is set by app.js in line 71, which is introduced by @AndrewPardoe.
@AndrewPardoe it's good that you're adding support for VC compilers. However, it would be nice to find information  in README.md that I have to create /mnt/c/tmp directory when I work with WSL, without digging into source code of compiler explorer:).

**Comment by AndrewPardoe** [comment] 2017-10-31 20:46
@admo, the WSL code is "warts and all". It's not a mainline scenario right now. I can look into creating better documentation for it, but reading the source is the only documentation right now. 

Hint: you'll also need your compiler set up in a particular fashion. LMK if you have issues.

**Comment by admo** [comment] 2017-10-31 21:54
I've just wanted to put there solution for @Vm900's issue. 

@AndrewPardoe I was affraid that this problem is caused by lack of support for some changes in [glibc](https://github.com/Microsoft/WSL/issues/1878). Happily, it was caused by non-existing directory:). And I started reading the JS code (for the first time in my life).

Maybe the solution would be to add WSL-mode option to the configuration, which will be disabled by default. Then the Compiler Explorer will work  out of the box even on WSL without additional tweaks of the environment. People, who want to have VC compiler, should enable WSL mode in configuration file, where they could find additional comment about creating /mnt/c/tmp. Just an idea.

**Comment by AndrewPardoe** [comment] 2017-10-31 22:51
Good suggestion, @admo.  Please see PR #603. It could use some testing : )

**Comment by admo** [comment] 2017-11-02 09:14
@AndrewPardoe, I've tested it, and it works. Thank you.

**Comment by mattgodbolt** [comment] 2017-12-20 14:34
Closing - if you still have problems please let me know @admo :)

**Closed by mattgodbolt** 2017-12-20 14:34 UTC
Labels: question, waiting
