### ISSUE TITLE
Bring back old diagnostics overlay a la Xcode

### ISSUE THREAD

**Issue by solodon4** [mattgodbolt/compiler-explorer#403] opened 2017-04-25 22:26 UTC
The new diagnostics overlay with just squiggles is not useful at all: I have to hover over each of them to see what error is reported where and from which compiler. In a scenario with 4 windows for all major compilers it becomes very hard to track which compiler fails on which line. With 4 extra windows with outputs from each of those compilers it becomes a mess to see what message is from where. 

The previous diagnostics similar to that of Xcode with different colors per compiler was much more useful for this scenario as I could immediately see on a piece of code which compiler fails where.

Thank you!
Yuriy

**Comment by mattgodbolt** [comment] 2017-04-25 22:37
Duplicate of #378. But has a better explanation of why people might like it. Short answer is that the new editor we use doesn't support errors in the same way but we hope to bring them back as a configuration option.

**Comment by mattgodbolt** [comment] 2017-04-25 23:04
Do be aware you can hit F8 to cycle through the errors/warnings from the keyboard. Not quite what you want I'm sure but maybe enough until we fix #378 .

Closing as a duplicate.

**Closed by mattgodbolt** 2017-04-25 23:04 UTC
Labels: question
