### ISSUE TITLE
Wrong highlighting for std::atomic<int> on gcc?

### ISSUE THREAD

**Issue by danra** [mattgodbolt/compiler-explorer#1312] opened 2019-03-20 15:31 UTC
See https://godbolt.org/z/6_Wl0h

Shouldn't the `mov`s and the `mfence` generated by gcc to be associated with the assignment to `i`?

Aside: DAK if it's an optimizer issue that gcc doesn't eliminate the memory fence completely like Clang does?

**Comment by partouf** [comment] 2019-03-22 02:40
Unfortunately, the GCC assembly assigns the line to atomic_base.h (because of inlining etc) - so technically it's not wrong.

Though there is enough information in the assembly to assign it to a user sourcecode line as well. Not sure how to get that to work, but maybe we can do that.

**Comment by mattgodbolt** [comment] 2019-11-12 04:05
I think this is "working as intended" -- we show the compiler's interpretation of where asm lines came from. We "know" that the `xchg` comes from the `atomic` header file, and as @partouf says that's not in the user's code, so it doesn't get highlighted. I don't know if in general we could discern the "original" code the inlined code came from, I don't think there's enough information to be 100% sure.

**Closed by mattgodbolt** 2019-11-12 04:05 UTC
Labels: enhancement
