### ISSUE TITLE
[BUG] Boost isn't available with MS compiler

### ISSUE THREAD

**Issue by pps83** [mattgodbolt/compiler-explorer#1860] opened 2020-02-26 11:19 UTC
Sample code: https://godbolt.org/z/iur_Ft

Even though I selected the only available `vcpkg 2019.07` option for boost (that's kind of weird, instead of proper list of boost versions like clang has):
![image](https://user-images.githubusercontent.com/1614246/75339977-64c7eb80-5846-11ea-9498-9061d557251c.png)

 I got compilation error saying that: `boost/config/user.hpp` is missing:

```
example.cpp

C:/data/libraries/installed/x64-windows/include\boost/config.hpp(30): fatal error C1083: Cannot open include file: 'boost/config/user.hpp': No such file or directory

Compiler returned: 2
```

**Comment by mattgodbolt** [comment] 2020-02-26 14:20
Thanks for reportin, I think this is a duplicate of #1362

**Closed by mattgodbolt** 2020-02-26 14:20 UTC
Labels: bug
