### ISSUE TITLE
CL compiler seems to have stopped working: Remote compilation failed: Bad Gateway

### ISSUE THREAD

**Issue by ChopsII** [mattgodbolt/compiler-explorer#231] opened 2017-01-11 00:21 UTC
As the title says. 
CL with 32 or 64 bit both result in that, while clang and gcc are still both working for me.

**Comment by ChopsII** [comment] 2017-01-11 01:48
It seems to have started working again

**Comment by mattgodbolt** [comment] 2017-01-11 19:23
Thanks; I think there are some site stability problems that could explain this. (It's not CL specific I don't think)

**Comment by mattgodbolt** [comment] 2017-01-11 19:24
Possibly a duplicate of #228

**Comment by mattgodbolt** [comment] 2017-01-11 22:47
Closing as I believe it'll either be fixed with #232 or #228

**Comment by ChopsII** [comment] 2017-01-11 23:05
(hopefully this doesn't reopen the ticket automatically because i'm just giving some feedback)

Just got this again in CL, despite #232 being marked fixed & deployed. Hopefully it's #228 then.

I had previously seen it in the other compilers too, but it was far more rare.

**Comment by mattgodbolt** [comment] 2017-01-11 23:21
I'm going to reopen; sounds like it's a separate issue after all. Thanks!

**Comment by mattgodbolt** [comment] 2017-01-12 14:18
@ChopsII : Next time it happens can you grab a URL and share it (if it's sensitive you can email it to me). I can't get it to happen at the moment. Can you also see if reloading the page makes it go away; and also tell me if there's anything in the Javascript console of your browser? Thanks!

**Comment by mattgodbolt** [comment] 2017-11-29 15:07
Closing, as not seen this or heard any issue with it since.

**Closed by mattgodbolt** 2017-11-29 15:07 UTC
Labels: bug

**Comment by kunaltyagi** [comment] 2020-02-04 09:33
I used [excerpt from PCL](https://godbolt.org/z/qV-bdM) to reproduce this failure (confirmed with 19.16 only, 32 and 64 bit). Code is compiled successfully by GCC 5.4 and clang (8, 7)

Changes made:
* `std::string` to `int` to reduce headers for MSVC to parse
* changed headers to include only what's used
