### ISSUE TITLE
AVR gcc

### ISSUE THREAD

**Issue by thielj** [mattgodbolt/compiler-explorer#301] opened 2017-03-03 13:55 UTC
Hi, great site/idea! 

Having a more recent AVR gcc would be helpful, e.g Arduino currently uses 4.8.1. 
Ubuntu should have prebuilt binaries for 4.8.1 and 4.9.2.

**Comment by thielj** [comment] 2017-06-13 12:22
This is my current 'wish list' for avr-gcc. Please let me know if/how I can help with this, @mattgodbolt

4.8.x (Atmel 3.4.x toolchain, also shipped with Arduino IDE) 
4.9.x (Atmel's 3.5.x toolchain; improved C++11 support)
5.x (Atmel's 3.6.x toolchain; additional devices; full C++11 support, C++14 experimental)
6.x (full C++14 support, C++17 experimental)

**Comment by TartanLlama** [comment] 2017-06-13 12:42
I've had AVR GCC 6 working with C++17 support, so can provide help too.

**Comment by mattgodbolt** [comment] 2017-07-11 15:10
All the compilers are installed by a script in https://github.com/mattgodbolt/compiler-explorer-image. Pull requests to cause the compilers you'd like to be installed somewhere in `/opt/compiler-explorer/` would be welcomed: then I can update the site with those compilers!

**Comment by martinmoene** [comment] 2018-07-08 07:01
I'm using [AVR-GCC 8.1.0 for Windows 32 and 64 bit](http://blog.zakkemble.co.uk/avr-gcc-builds/). Could the build script listed there be of help?

**Comment by mattgodbolt** [comment] 2018-07-14 22:21
Some useful links there. Anyone able to volunteer to build and test more modern AVR compilerss? I don't have the time myself, but so long as one can get a script to build the compiler and make it look like the existing scripts in the above image repo, that's great. I'd happily accept a PR to build and install more AVR compilers.

**Comment by conklech** [comment] 2018-12-01 01:09
I spent longer than I'd like to admit trying to figure out how compiler-explorer-image actually acquires new compilers. It looks like the first thing to do is add a new configuration file in gcc-cross/build/1.22.0 and run the gcc-cross Docker build. Am I on the right track?

**Comment by mattgodbolt** [comment] 2018-12-01 13:00
Yes, that's the one! Thanks for your persistence in finding how things are done! A new file in the gcc-cross directory with the crosstool-ng config, then a change to the build script at the top level (the build cross compilers shell script)

**Comment by fabiocannizzo** [comment] 2019-03-18 08:47
This seems a duplicate of #1266

**Comment by pixxon** [comment] 2019-03-24 21:50
Yes, however here crosstool-ng is used, while I got it working by building from zero.
( Like a simple gcc, even using the same script. )
It should have the same versions as gcc, except if something goes wrong.
Currently I build 8.3.0, I guess it's not that much of a problem.

Some sidenote: avr backend is in clang-8.

**Closed** 2019-09-30 23:50 UTC
Labels: help wanted, new-compilers
