### ISSUE TITLE
msp430 headers missing

### ISSUE THREAD

**Issue by beached** [mattgodbolt/compiler-explorer#385] opened 2017-04-17 19:59 UTC
I am trying to include the msp430.h header and it is showing as missing.  I am using the gcc 6.2.1 msp430 compiler from the gcc.godbot.org site https://godbolt.org/g/Vwbpz6

**Comment by mattgodbolt** [comment] 2017-04-18 12:47
Thanks; will look at getting fixed!

**Comment by mattgodbolt** [comment] 2017-04-18 12:49
Is that a header file provided by the vendor themselves? It doesn't appear to be part of the GCC distribution? @lefticus any ideas?

**Comment by mattgodbolt** [comment] 2017-04-18 12:51
```:/opt/compiler-explorer$ find msp* -name msp430.h
msp430/gcc-4.5.3/lib/gcc/msp430/4.5.3/plugin/include/config/msp430/msp430.h
msp430-gcc-5.3.0.219_linux32/lib/gcc/msp430-elf/5.3.0/plugin/include/config/msp430/msp430.h
msp430-gcc-6.2.1.16_linux64/lib/gcc/msp430-elf/6.2.1/plugin/include/config/msp430/msp430.h
``` is all I can find =)

**Comment by beached** [comment] 2017-04-18 12:58
On my phone now but i did some further looking and there are more and they are part of the BSP that TI installs with CCS it seems.  I saw a version on Jason Turners C++ videos using them though, so maybe they can be obtained another way

**Comment by lefticus** [comment] 2017-04-18 13:10
It's still this issue: #299 needing the support files.

**Comment by mattgodbolt** [comment] 2017-04-18 13:24
Oh whoops! I had completely forgotten about that! Closing this as a duplicate of #299

**Closed by mattgodbolt** 2017-04-18 13:24 UTC
Labels: bug, compiler-issue
