### ISSUE TITLE
Compiler times out

### ISSUE THREAD

**Issue by ruipacheco** [mattgodbolt/compiler-explorer#776] opened 2018-01-17 21:32 UTC
Compiler times out when building this with Boost:

```
#include <memory>
#include <boost/asio.hpp>
#include <system_error>
#include <chrono>

struct listener : public std::enable_shared_from_this<listener> {
    explicit listener() : resolver_{service_} {
        const boost::asio::ip::tcp::resolver::query query("192.168.0.255", "5432");
        std::error_code ec;
        resolver_.async_resolve(query, [&](const std::error_code &ec_, boost::asio::ip::tcp::resolver::iterator iter) {
          if (ec_) {
            ec = ec_;
            return;
          }
          while (iter != boost::asio::ip::tcp::resolver::iterator()) {
            socket_.reset(new boost::asio::generic::stream_protocol::socket(service_));
            socket_->async_connect((*iter++).endpoint(), [&](const std::error_code &err_code) {
              if (err_code) {
                ec = err_code;
                return;
              }
            });
          };
        });
        if (ec) {
          return;
        }
        // Resolver timer
        std::chrono::seconds sec{3};
        boost::asio::steady_timer resolver_timer(service_);
        resolver_timer.expires_from_now(sec, ec);
        if (ec) {
          return;
        }
        resolver_timer.async_wait([&](const std::error_code &ec_) {
          if (!connected) {
            if (ec_) {
              ec = ec_;
              return;
            }
            resolver_.cancel();
          }
        });

        service_.run();
        service_.reset();
    }
    boost::asio::io_service service_;
    std::unique_ptr<boost::asio::generic::stream_protocol::socket> socket_;
    boost::asio::ip::tcp::resolver resolver_;
};

int main() { 
}
```

**Comment by mattgodbolt** [comment] 2018-01-17 22:19
Thanks for this.

I think this is a duplicate of #730 - compiling anything in boost is super slow in general (taking a few seconds on my super fast desktop machine), and even more so as CE has its libraries on an NFS mount. I'm hoping to fix that sometime though, which is tracked in #730.

**Closed by mattgodbolt** 2018-01-17 22:19 UTC
