### ISSUE TITLE
Incomplete AST view for global variables

### ISSUE THREAD

**Issue by pgoodman** [mattgodbolt/compiler-explorer#1360] opened 2019-04-21 02:06 UTC
```c
extern int a, b, c;
int *x = &b;
```

produces the following:

```
TranslationUnitDecl
|-VarDecl <line:1:1, col:12> col:12 a 'int' extern
```

**Comment by mattgodbolt** [comment] 2019-04-24 13:36
@TartanLlama do you happen to know if this is a CE problem or a clang issue? Thanks!

**Comment by steveire** [comment] 2019-04-25 09:56
It is a CE issue. The cause is probably in the same place as https://github.com/mattgodbolt/compiler-explorer/issues/1346. I'd even call this issue a duplicate of that one.

**Comment by mattgodbolt** [comment] 2019-06-18 03:09
Closing as a duplicate (if only to keep the bug count down!)

**Closed by mattgodbolt** 2019-06-18 03:09 UTC
Labels: bug, help wanted
