### ISSUE TITLE
ASM output needs to be line-trimmed for diffs

### ISSUE THREAD

**Issue by lefticus** [mattgodbolt/compiler-explorer#282] opened 2017-02-16 15:32 UTC
See this example from the beta site

https://godbolt.org/g/h9hVT1

GCC seems to pad the lines with spaces, while ICC does not, so the diff looks bigger than it should.

**Comment by mattgodbolt** [comment] 2017-02-16 15:41
Right...somewhat of a duplicate of #269 - will update that with this info

**Comment by lefticus** [comment] 2017-02-16 15:42
Oops, sorry :D

**Closed by mattgodbolt** 2017-02-16 15:41 UTC
