### ISSUE TITLE
[BUG] Abseil Container Includes Not Found

### ISSUE THREAD

**Issue by Xelous** [mattgodbolt/compiler-explorer#1709] opened 2019-11-27 22:49 UTC
** Description **
Including some of the abseil containers fails to find the related headers, btree is the area I've personally been looking at, for instance these two headers are not available:

#include <absl/container/btree_map.h>
#include <absl/container/btree_set.h>

Inclusion of other abseil headers are present and correct, such as <absl/hash/hash.h>.

** Reproduction **
Reproduction via this code snippet:

`#include <iostream>
#include <string>
#include <vector>
#include <absl/container/btree_map.h>
#include <absl/container/btree_set.h>

int main()
{
	absl::btree_set<std::string> set = { {"huey"}, {"dewey"}, {"louie"}};

	for(const auto& item : set)
	{
		std::cout << item << "\r\n";
	}
}`

 ** Expected **
The compilation should complete.

** Links **
https://godbolt.org/z/Q4s4Zp

**Comment by apmorton** [comment] 2019-11-27 23:03
This only happens on microsofts msvc compilers - as those are operated by microsoft and they are responsible for updating the libraries included.

The version of absl is from right before those headers landed publicly, so this is technically working as intended - its just an out of date absl version (the version shown in the dropdown is `vcpkg 2019.07` and those headers landed in august).

If you use a compiler that is run by CE (anything except the native MSVC ones) you will get the latest absl and it works as expected: https://godbolt.org/z/VGatuA

**Comment by Xelous** [comment] 2019-11-27 23:13
Thank you for that very speedy, and useful, reply!

What a shame though I'm trying to explore (no pun intended) a problem with an MSVC specific pathway in the library :(

**Comment by apmorton** [comment] 2019-11-27 23:32
if the old versions of MSVC also have the bug you should be able to use the wine versions: https://godbolt.org/z/FxhDT_

**Comment by mattgodbolt** [comment] 2019-12-03 04:23
Thanks all: gonna close this for now.

**Closed by mattgodbolt** 2019-12-03 04:23 UTC
Labels: bug
