### ISSUE TITLE
<lang>.godbolt.org automatically sets language <lang>

### ISSUE THREAD

**Issue by JohanEngelen** [mattgodbolt/compiler-explorer#735] opened 2018-01-03 19:32 UTC
Before the unification of languages, d.godbolt.org would automatically select D, gcc.godbolt.org would select C++, etc.
I personally find it a little annoying that I can no longer browse to d.godbolt.org and see my previous D code, while at the same time using gcc.godbolt.org and immediately seeing my previous C++ code.  (I happen to use both a lot)
At the very least, I would expect d.godbolt.org to select D as the language, and gcc.godbolt.org C++, etc.

Thanks!
  Johan

**Comment by mattgodbolt** [comment] 2018-01-03 19:36
Hi Johan,

We thought long and hard about this, before punting on it for now. I agree, d.godbolt.org would be better to redirect to default to D.

However, this causes a lot of confusion, as you can bring up C++ in d.godbolt.org (and indeed the URL is rewritten to godbolt.org).

If it helps, there's an option in the settings to set a default language.

New languages moving on won't have a URL associated with them.

We can definitely discuss making changes. One thing would be to not redirect to godbolt.org for language-specific links, and then use the URL in the browser to determine the "default" language. We currently decided to stick to a unified URL though.

I agree the loss of having separate storage for gcc.godbolt.org vs d.godbolt.org is annoying though. We will discuss. Not redirecting to godbolt.org would potentially solve this. Thanks for your feedback!

**Comment by JohanEngelen** [comment] 2018-01-03 19:53
>  However, this causes a lot of confusion, as you can bring up C++ in d.godbolt.org

When selecting C++ during a session, short-term memory should help prevent confusion ;)
I do find it confusing when clicking on an external link: "Look at this awesome website! Rust to asm! rust.godbolt.org" that then shows C++ code! ;-)  (or whatever language is stored in the user's cache).

I don't know all issues involved, so can't make a good judgement. The new behavior personally immediately struck me as awkward, but it may be tied to my workflow.
Thanks for reconsidering :)

**Comment by CryZe** [comment] 2018-01-03 20:02
I feel like it would maybe make more sense to be able to store different "workflows" that you can then later load. Sometimes when working on C++ I just want the code and the asm, while sometimes I care more about the LLVM IR, so I want to see that instead. A different time I work on Rust and don't want to see C++ at all, and sometimes I want to compare them. So being able to store these configurations somehow is probably better. rust.godbolt.org could then redirect to godbolt.org with a default rust workflow loaded.

**Comment by partouf** [comment] 2018-01-03 20:13
I like the workflows suggestion, maybe where it also stores things like compiler options and libraries.

Even better would be if it would periodically be saved. I was working on something in CE trying to compare 2 languages yesterday with a godbolt link as my basis, but I kept accidentally backswiping on my touchpad so the history of the browser would go back, and I had to setup my environment all over again.

**Comment by RabsRincon** [comment] 2018-01-03 20:31
@partouf Note that the state is saved pretty much in every change, but it's getting overwritten when you load back the url :( (If you closed and reopened Godbolt, you would see the same than when you closed it)

I'm currently looking for a way to do what @JohanEngelen suggested. Thanks for your patience :)

**Comment by mattgodbolt** [comment] 2018-01-03 20:32
See also #220

**Comment by mattgodbolt** [comment] 2018-01-05 16:20
Here's a thought:

* No longer redirect <lang>.godbolt.org to godbolt.org. This means each subdomain gets its own settings (including stored previous state).
* If there's no setting for "Default language" the JS code "guesses" from the domain name its served from. A simple hacky lookup of URLs should do the trick. That way folks hitting `rust.godbolt.org` for the first time get `rust` as the default language, etc.
* Short URLs only encode `godbolt.org` and remain so. This is potentially confusing but facilitates some changes down the line (e.g. unfurling). It means if you click a short link you'll end up on godbolt.org (not any lang.godbolt.org, even if you created the link on e.g. rust.godbolt.org).

**Comment by JohanEngelen** [comment] 2018-01-05 20:25
Sounds good.

**Comment by mattgodbolt** [comment] 2018-01-05 20:55
Johan; we've deployed this to beta, can you check out <your urls of
choice>/beta e.g. https://ldc.godbolt.org/beta and see if they do things a
better way for you?

**Comment by RabsRincon** [comment] 2018-01-05 21:03
We're aware of C++ being set regardeless of the chosen lang. Working on a fix right now

**Comment by RabsRincon** [comment] 2018-01-05 22:47
Should now be fixed. Please feel free to give it a try and share your thoughts with us :)

**Comment by RabsRincon** [comment] 2018-01-05 22:55
Should now be fixed. Please feel free to give it a try and share your thoughts with us :)

**Comment by JohanEngelen** [comment] 2018-01-06 11:32
https://d.godbolt.org/beta/  loads a D compiler, cpp.godbolt.org loads C++, but both don't succeed in compiling:  `<Remote compilation failed: Error sending request>`

**Comment by RabsRincon** [comment] 2018-01-06 11:36
We're currently experiencing some problems on the beta instances unreleated to this change. I'm trying to work out what and fix it. I'll let you know when those are resolved so you can take a look again :)

**Comment by RabsRincon** [comment] 2018-01-06 14:30
Beta should now be fixed. Thanks for your patience

**Comment by JohanEngelen** [comment] 2018-01-07 15:02
It's better now I think. What I tested:
1. Open new tab with d.godbolt.org --> starts with D selected, with an example, with LDC compiler
2. Switch to C++
3. Close tab
4. Open new tab with d.godbolt.org --> starts with C++ selected (this isn't so bad)
5. Switch to D --> no compiler selected (perhaps fix it so it selects the previous/default compiler?)

**Comment by RabsRincon** [comment] 2018-01-07 15:50
Thanks for your input. While I think we won't be able to fix your 4th item, item 5 is an error in our side. Note that the default compiler is not being respected if you Restart the UI, which is probably releated to it

**Comment by RabsRincon** [comment] 2018-01-07 16:25
Thanks for your input. While I think we won't be able to fix your 4th item, as that's intended behaviour, item 5 is a sideffect of being on the beta branch, which currently lacks LDC 1.7.0. If this is the only issue you've found, I think we're ready to merge to master.

Again, thank you so so much for taking the time to improve CE :)

**Comment by RabsRincon** [comment] 2018-01-08 19:33
This behvaiour is now implemented in the site. We'll keep iteration over some of this stuff for a bit until we get it to a perfect state. We could have not done it without your input 🥇

**Closed by RabsRincon** 2018-01-08 19:33 UTC
Labels: enhancement, question, ui
