### ISSUE TITLE
Website is completely unusable on mobile

### ISSUE THREAD

**Issue by yuriks** [mattgodbolt/compiler-explorer#699] opened 2017-12-21 18:06 UTC
The editor seems to be completely unusable in Android atm. Backspacing or typing doesn't delete characters, and in addition seems to randomly insert copies of the editor text on the cursor position, making editing any text impossible. This happens even with auto-completion disabled in the settings.

In addition, there seems to be some aggressive mouse event handler installed which prevents the page from being scrolled or zoomed when touching above any UI. This again renders the page unusable if you happen to accidently zoom in over an editor, because now you can't change your viewport anymore.

It would be great if this were fixed, even if it's just by completely disabling the fancy editor and showing stuff using plain textareas.

**Comment by mattgodbolt** [comment] 2017-12-21 18:09
Duplicate of #176 - we are still not really prioritising this as the editor we use explicitly doesn't want to support mobile :(.  Adding code to handle both a "rich text" editor and a simple editor could work, but really the issue is most CE links are meant for big widescreen monitors and no amount of cleverness makes that work on a portrait small screen.

**Closed by mattgodbolt** 2017-12-21 18:09 UTC
