### ISSUE TITLE
Can't zoom in on mobile

### ISSUE THREAD

**Issue by jonesmz** [mattgodbolt/compiler-explorer#1070] opened 2018-09-09 17:37 UTC
When visiting compiler explorer links on my android phone with the google chrome browser, I am unable to zoom in. This means the website is effectively useless on mobile. The text is incredibly tiny

**Comment by mattgodbolt** [comment] 2018-09-10 13:13
There are many issues with mobile, unfortunately: See #176 for example amongst others. Thanks for the report; I'm closing this as a duplicate of #176.

**Closed by mattgodbolt** 2018-09-10 13:13 UTC
