### ISSUE TITLE
[REQUEST] Filter out compilers from Execution pane when it doesn't support execution

### ISSUE THREAD

**Issue by partouf** [mattgodbolt/compiler-explorer#1650] opened 2019-10-27 13:07 UTC
For example, the msvc compilers have the property "supportsExecute": false, but they still appear in the compiler selection combobox.

There could be alternatives to solve this, but considering calls get proxied straight through the MS instance, there isn't a lot of room there maybe.

**Comment by RabsRincon** [comment] 2019-10-27 23:23
Duplicate of #1506

**Closed by RabsRincon** 2019-10-27 23:23 UTC
Labels: request
