### ISSUE TITLE
Can't include boost when using MSVC

### ISSUE THREAD

**Issue by k15tfu** [mattgodbolt/compiler-explorer#1362] opened 2019-04-22 10:20 UTC
https://godbolt.org/z/d4kNA0

It says:
```
<source>(3): fatal error C1083: Cannot open include file: 'boost/preprocessor.hpp': No such file or directory
```

**Comment by mattgodbolt** [comment] 2019-04-22 12:55
This is a duplicate of #1168

**Closed by mattgodbolt** 2019-04-22 12:55 UTC
