### ISSUE TITLE
[BUG] simple C++ fmtlib example compiles does not execute

### ISSUE THREAD

**Issue by summivox** [mattgodbolt/compiler-explorer#1930] opened 2020-04-22 19:22 UTC
**Describe the bug**
A simple C++ example using fmtlib compiles but does not execute.

**To Reproduce**

```c++
#include <string>

#include <fmt/format.h>

int main() {
  const std::string s = fmt::format("The answer is {}.", 42);
  fmt::print("The answer is {}.", 42);
  return 0;
}
```

Pick the `{fmt}` in the library picker in both compile and execution panels.

**Expected behavior**
Program compiles and executes correctly.

**Link**
https://godbolt.org/z/PCoSdK

**Screenshots**
![image](https://user-images.githubusercontent.com/1770521/80024357-c34ec600-8493-11ea-9a1e-88ca2cb55019.png)
![image](https://user-images.githubusercontent.com/1770521/80024406-dcf00d80-8493-11ea-8571-e9204d20b5cc.png)

**Desktop (please complete the following information):**
 - OS: Win10, Ubuntu 16.04
 - Browser: Firefox
 - Version: 75.0

**Additional context**
N/A

**Comment by mattgodbolt** [comment] 2020-04-22 19:35
We don't yet support linking with libraries for execution, I'm sorry. Duplicate of #1662

**Closed by mattgodbolt** 2020-04-22 19:35 UTC
Labels: bug
