### ISSUE TITLE
Is linking of builtins supported/possible for C?

### ISSUE THREAD

**Issue by lesshaste** [mattgodbolt/compiler-explorer#258] opened 2017-02-03 13:14 UTC
If we look at https://godbolt.org/g/2Tk9lh we can see this appears a few times.

 call    __divdc3

It would be great if there were an option to link that builtin so the assembly is included in the window.

Is that possible?

**Comment by mattgodbolt** [comment] 2017-02-03 17:44
Hi! How do you mean about linking with that builtin? As best I can tell, the `__divdc3` function is an externally-defined function in `libc`.

**Comment by lesshaste** [comment] 2017-02-03 20:50
It may not be possible (my terminology also wasn't right)  .  http://stackoverflow.com/questions/15502403/where-do-i-find-the-assembly-code-for-a-procedure-called-in-the-gcc-assembly-out seems to have an answer.

**Comment by mattgodbolt** [comment] 2017-02-03 21:21
Right - the functionality is provided in an external library. You can see a little more if you use binary mode: https://godbolt.org/g/YmffId but all you really see is the [PLT](https://www.technovelty.org/linux/plt-and-got-the-key-to-code-sharing-and-dynamic-libraries.html) that is the thunk to go to a shared object.

Passing `-static` might fix that but for some other reason that's not working (I'll file a new bug for that).

**Comment by pcordes** [comment] 2017-07-31 03:00
The linker command-line for binary mode must be weird.  `__divdc3` is defined in `libgcc.a`, and is normally statically linked into an executable.  (I confirmed that on my desktop (Arch Linux) with clang 4.0.1, appending `int main(void){}` to the source from your link).

`clang -O3 foo.c && objdump -drwC -Mintel a.out`:

```
0000000000400460 <f>:
  ...
  400478:       e8 83 00 00 00          call   400500 <__divdc3>
```

Note the direct `call`, not via the PLT.

The function itself is right there in the binary:

```
0000000000400500 <__divdc3>:
  400500:       f3 0f 7e 3d b8 03 00 00         movq   xmm7,QWORD PTR [rip+0x3b8]        # 4008c0 <_IO_stdin_used+0x20>
  400508:       66 0f 28 f1             movapd xmm6,xmm1
  40050c:       66 0f 28 e3             movapd xmm4,xmm3
```

`clang -v` shows that it's linker command-line included:

```
 /tmp/foo-009704.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s
 --no-as-needed /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/crtend.o
  /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.1.1/../../../../lib64/crtn.o
```

If the compiler-explorer binary-mode is producing executables that call those helper functions via the PLT, probably you left out `-lgcc`, and only used `-lgcc_s`.  (There is a `/usr/lib/libgcc_s.so.1`, which also contains that function).  I think the idea behind linking them statically is that they can end up inside hot loops where programmers weren't expecting them, and calling them via the PLT is an extra level of indirection.  Or maybe it's so gcc can change their behaviour, and make code that depends on how it knows the function will behave, because it knows it will be using the version that came with that version of gcc.  But that's probably not the case, or clang couldn't just use gcc's library.)

@lesshaste: you can `disas /usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/libgcc.a` locally to get the same thing.  (`alias disas='objdump -drwC -Mintel'`).

**Comment by mattgodbolt** [comment] 2019-10-26 17:16
Updating as in the intervening years (sorry), the trunk build has inlined. https://godbolt.org/z/3sPIul still shows the issue.

**Comment by mattgodbolt** [comment] 2019-10-26 17:23
https://godbolt.org/z/kKE_4X -- re: @pcordes comments about static linking, you're right. I think CE's filtering is dropping what it thinks is an unused function! Filing a new bug for that, and will close this one in favour of it

**Closed by mattgodbolt** 2019-10-26 17:23 UTC
Labels: compiler-issue, question
