### ISSUE TITLE
[BUG] MSVC conformace view always reports warning

### ISSUE THREAD

**Issue by Yankes** [mattgodbolt/compiler-explorer#1773] opened 2020-01-10 22:55 UTC
In correct build output of MSVC compiler is never empty.
e.g.
```
example.cpp
```
godbolt interpreted this as warning:

https://github.com/mattgodbolt/compiler-explorer/blob/08f3b55eb5dd6f15831c98e19671cee45968cf73/static/panes/conformance-view.js#L266-L268

Could be possible to filter it out? (or better not send it to UI)

**Comment by mattgodbolt** [comment] 2020-01-10 23:33
I think a duplicate of #1034 ?

**Closed** 2020-01-10 23:33 UTC
Labels: Windows, bug
