### ISSUE TITLE
Add spacing between address and opcodes in binary view

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#560] opened 2017-10-08 13:03 UTC
As requested via email; they're a bit close together.

**Comment by RabsRincon** [comment] 2017-10-08 13:21
Can't do much until https://github.com/Microsoft/monaco-editor/issues/515 is adressed, as it would become unreadable if spacing was to be added

**Comment by RabsRincon** [comment] 2018-03-06 08:32
Duplicate of #484

**Closed by RabsRincon** 2018-03-06 08:32 UTC
Labels: tracking, ui
